theme: jekyll-theme-cayman
title: Is Environment a New Human Development Validated by Economic Complexity?
description: An Exploratory Study of Economic Complexity and Human Development Indicators
description: Lily Yue
